 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace MSBC2S
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID OnLoginRequest = (Nettention.Proud.RmiID)5000+1;
			public const Nettention.Proud.RmiID OnRegisterRequest = (Nettention.Proud.RmiID)5000+2;
			public const Nettention.Proud.RmiID OnStatusRequest = (Nettention.Proud.RmiID)5000+3;
			public const Nettention.Proud.RmiID OnSoloQueueRequest = (Nettention.Proud.RmiID)5000+4;
			public const Nettention.Proud.RmiID OnTeamQueueRequest = (Nettention.Proud.RmiID)5000+5;
			public const Nettention.Proud.RmiID OnQuitQueueRequest = (Nettention.Proud.RmiID)5000+6;
			public const Nettention.Proud.RmiID OnGameInfoRequest = (Nettention.Proud.RmiID)5000+7;
			public const Nettention.Proud.RmiID OnGameActionReady = (Nettention.Proud.RmiID)5000+8;
			public const Nettention.Proud.RmiID OnGameActionDamage = (Nettention.Proud.RmiID)5000+9;
			public const Nettention.Proud.RmiID OnGameActionObject = (Nettention.Proud.RmiID)5000+10;
			public const Nettention.Proud.RmiID OnGameActionItem = (Nettention.Proud.RmiID)5000+11;
			public const Nettention.Proud.RmiID OnGameUserMove = (Nettention.Proud.RmiID)5000+12;
			public const Nettention.Proud.RmiID OnGameUserSync = (Nettention.Proud.RmiID)5000+13;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			OnLoginRequest,
			OnRegisterRequest,
			OnStatusRequest,
			OnSoloQueueRequest,
			OnTeamQueueRequest,
			OnQuitQueueRequest,
			OnGameInfoRequest,
			OnGameActionReady,
			OnGameActionDamage,
			OnGameActionObject,
			OnGameActionItem,
			OnGameUserMove,
			OnGameUserSync,
		};
	}
}

				 
