 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace MSBC2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID OnGameMove = (Nettention.Proud.RmiID)6000+1;
			public const Nettention.Proud.RmiID OnGameSync = (Nettention.Proud.RmiID)6000+2;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			OnGameMove,
			OnGameSync,
		};
	}
}

				 
