




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;	     

namespace MSBC2C
{
	internal class Stub:Nettention.Proud.RmiStub
	{
public AfterRmiInvocationDelegate AfterRmiInvocation = delegate(Nettention.Proud.AfterRmiSummary summary) {};
public BeforeRmiInvocationDelegate BeforeRmiInvocation = delegate(Nettention.Proud.BeforeRmiSummary summary) {};

		public delegate bool OnGameMoveDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int room, String data);  
		public OnGameMoveDelegate OnGameMove = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int room, String data)
		{ 
			return false;
		};
		public delegate bool OnGameSyncDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int room, String data);  
		public OnGameSyncDelegate OnGameSync = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int room, String data)
		{ 
			return false;
		};
	public override bool ProcessReceivedMessage(Nettention.Proud.ReceivedMessage pa, Object hostTag) 
	{
		Nettention.Proud.HostID remote=pa.RemoteHostID;
		if(remote==Nettention.Proud.HostID.HostID_None)
		{
			ShowUnknownHostIDWarning(remote);
		}

		Nettention.Proud.Message __msg=pa.ReadOnlyMessage;
		int orgReadOffset = __msg.ReadOffset;
        Nettention.Proud.RmiID __rmiID = Nettention.Proud.RmiID.RmiID_None;
        if (!__msg.Read( out __rmiID))
            goto __fail;
					
		switch(__rmiID)
		{
        case Common.OnGameMove:
            ProcessReceivedMessage_OnGameMove(__msg, pa, hostTag, remote);
            break;
        case Common.OnGameSync:
            ProcessReceivedMessage_OnGameSync(__msg, pa, hostTag, remote);
            break;
		default:
			 goto __fail;
		}
		return true;
__fail:
	  {
			__msg.ReadOffset = orgReadOffset;
			return false;
	  }
	}
    void ProcessReceivedMessage_OnGameMove(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int room; Nettention.Proud.Marshaler.Read(__msg,out room);	
String data; Nettention.Proud.Marshaler.Read(__msg,out data);	
core.PostCheckReadMessage(__msg, RmiName_OnGameMove);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=room.ToString()+",";
parameterString+=data.ToString()+",";
        NotifyCallFromStub(Common.OnGameMove, RmiName_OnGameMove,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnGameMove;
        summary.rmiName = RmiName_OnGameMove;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnGameMove (remote,ctx , room, data );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnGameMove);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnGameMove;
        summary.rmiName = RmiName_OnGameMove;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnGameSync(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int room; Nettention.Proud.Marshaler.Read(__msg,out room);	
String data; Nettention.Proud.Marshaler.Read(__msg,out data);	
core.PostCheckReadMessage(__msg, RmiName_OnGameSync);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=room.ToString()+",";
parameterString+=data.ToString()+",";
        NotifyCallFromStub(Common.OnGameSync, RmiName_OnGameSync,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnGameSync;
        summary.rmiName = RmiName_OnGameSync;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnGameSync (remote,ctx , room, data );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnGameSync);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnGameSync;
        summary.rmiName = RmiName_OnGameSync;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_OnGameMove="OnGameMove";
public const string RmiName_OnGameSync="OnGameSync";
       
public const string RmiName_First = RmiName_OnGameMove;
#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_OnGameMove="";
public const string RmiName_OnGameSync="";
       
public const string RmiName_First = "";
#endif
		public override Nettention.Proud.RmiID[] GetRmiIDList { get{return Common.RmiIDList;} }
		
	}
}

