 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace MSBS2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID OnLoginResult = (Nettention.Proud.RmiID)4000+1;
			public const Nettention.Proud.RmiID OnRegisterResult = (Nettention.Proud.RmiID)4000+2;
			public const Nettention.Proud.RmiID OnStatusResult = (Nettention.Proud.RmiID)4000+3;
			public const Nettention.Proud.RmiID OnSoloMatched = (Nettention.Proud.RmiID)4000+4;
			public const Nettention.Proud.RmiID OnTeamMatched = (Nettention.Proud.RmiID)4000+5;
			public const Nettention.Proud.RmiID OnGameInfo = (Nettention.Proud.RmiID)4000+6;
			public const Nettention.Proud.RmiID OnGameStatusCountdown = (Nettention.Proud.RmiID)4000+7;
			public const Nettention.Proud.RmiID OnGameStatusTime = (Nettention.Proud.RmiID)4000+8;
			public const Nettention.Proud.RmiID OnGameStatusReady = (Nettention.Proud.RmiID)4000+9;
			public const Nettention.Proud.RmiID OnGameStatusScore = (Nettention.Proud.RmiID)4000+10;
			public const Nettention.Proud.RmiID OnGameStatusMessage = (Nettention.Proud.RmiID)4000+11;
			public const Nettention.Proud.RmiID OnGameEventHealth = (Nettention.Proud.RmiID)4000+12;
			public const Nettention.Proud.RmiID OnGameEventDamage = (Nettention.Proud.RmiID)4000+13;
			public const Nettention.Proud.RmiID OnGameEventObject = (Nettention.Proud.RmiID)4000+14;
			public const Nettention.Proud.RmiID OnGameEventItem = (Nettention.Proud.RmiID)4000+15;
			public const Nettention.Proud.RmiID OnGameEventKill = (Nettention.Proud.RmiID)4000+16;
			public const Nettention.Proud.RmiID OnGameEventRespawn = (Nettention.Proud.RmiID)4000+17;
			public const Nettention.Proud.RmiID OnGameResult = (Nettention.Proud.RmiID)4000+18;
			public const Nettention.Proud.RmiID OnGameUserMove = (Nettention.Proud.RmiID)4000+19;
			public const Nettention.Proud.RmiID OnGameUserSync = (Nettention.Proud.RmiID)4000+20;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			OnLoginResult,
			OnRegisterResult,
			OnStatusResult,
			OnSoloMatched,
			OnTeamMatched,
			OnGameInfo,
			OnGameStatusCountdown,
			OnGameStatusTime,
			OnGameStatusReady,
			OnGameStatusScore,
			OnGameStatusMessage,
			OnGameEventHealth,
			OnGameEventDamage,
			OnGameEventObject,
			OnGameEventItem,
			OnGameEventKill,
			OnGameEventRespawn,
			OnGameResult,
			OnGameUserMove,
			OnGameUserSync,
		};
	}
}

				 
