




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;

namespace MSBS2C
{
	internal class Proxy:Nettention.Proud.RmiProxy
	{
public bool OnLoginResult(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnLoginResult;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnLoginResult, Common.OnLoginResult);
}

public bool OnLoginResult(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnLoginResult;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnLoginResult, Common.OnLoginResult);
}
public bool OnStatusResult(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnStatusResult;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnStatusResult, Common.OnStatusResult);
}

public bool OnStatusResult(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnStatusResult;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnStatusResult, Common.OnStatusResult);
}
public bool OnSystemResult(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnSystemResult;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnSystemResult, Common.OnSystemResult);
}

public bool OnSystemResult(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnSystemResult;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnSystemResult, Common.OnSystemResult);
}
public bool OnGameMatched(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameMatched;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameMatched, Common.OnGameMatched);
}

public bool OnGameMatched(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameMatched;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameMatched, Common.OnGameMatched);
}
public bool OnGameInfo(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameInfo;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameInfo, Common.OnGameInfo);
}

public bool OnGameInfo(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameInfo;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameInfo, Common.OnGameInfo);
}
public bool OnGameStatusCountdown(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameStatusCountdown;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameStatusCountdown, Common.OnGameStatusCountdown);
}

public bool OnGameStatusCountdown(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameStatusCountdown;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameStatusCountdown, Common.OnGameStatusCountdown);
}
public bool OnGameStatusTime(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameStatusTime;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameStatusTime, Common.OnGameStatusTime);
}

public bool OnGameStatusTime(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameStatusTime;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameStatusTime, Common.OnGameStatusTime);
}
public bool OnGameStatusReady(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameStatusReady;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameStatusReady, Common.OnGameStatusReady);
}

public bool OnGameStatusReady(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameStatusReady;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameStatusReady, Common.OnGameStatusReady);
}
public bool OnGameStatusScore(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameStatusScore;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameStatusScore, Common.OnGameStatusScore);
}

public bool OnGameStatusScore(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameStatusScore;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameStatusScore, Common.OnGameStatusScore);
}
public bool OnGameStatusMessage(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameStatusMessage;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameStatusMessage, Common.OnGameStatusMessage);
}

public bool OnGameStatusMessage(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameStatusMessage;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameStatusMessage, Common.OnGameStatusMessage);
}
public bool OnGameEventHealth(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameEventHealth;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameEventHealth, Common.OnGameEventHealth);
}

public bool OnGameEventHealth(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameEventHealth;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameEventHealth, Common.OnGameEventHealth);
}
public bool OnGameEventDamage(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameEventDamage;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameEventDamage, Common.OnGameEventDamage);
}

public bool OnGameEventDamage(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameEventDamage;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameEventDamage, Common.OnGameEventDamage);
}
public bool OnGameEventObject(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameEventObject;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameEventObject, Common.OnGameEventObject);
}

public bool OnGameEventObject(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameEventObject;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameEventObject, Common.OnGameEventObject);
}
public bool OnGameEventItem(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameEventItem;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameEventItem, Common.OnGameEventItem);
}

public bool OnGameEventItem(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameEventItem;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameEventItem, Common.OnGameEventItem);
}
public bool OnGameEventKill(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameEventKill;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameEventKill, Common.OnGameEventKill);
}

public bool OnGameEventKill(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameEventKill;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameEventKill, Common.OnGameEventKill);
}
public bool OnGameEventRespawn(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameEventRespawn;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameEventRespawn, Common.OnGameEventRespawn);
}

public bool OnGameEventRespawn(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameEventRespawn;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameEventRespawn, Common.OnGameEventRespawn);
}
public bool OnGameResult(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameResult;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameResult, Common.OnGameResult);
}

public bool OnGameResult(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameResult;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameResult, Common.OnGameResult);
}
public bool OnGameUserMove(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameUserMove;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameUserMove, Common.OnGameUserMove);
}

public bool OnGameUserMove(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameUserMove;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameUserMove, Common.OnGameUserMove);
}
public bool OnGameUserSync(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnGameUserSync;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, data);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnGameUserSync, Common.OnGameUserSync);
}

public bool OnGameUserSync(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String data)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnGameUserSync;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, data);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnGameUserSync, Common.OnGameUserSync);
}
#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_OnLoginResult="OnLoginResult";
public const string RmiName_OnStatusResult="OnStatusResult";
public const string RmiName_OnSystemResult="OnSystemResult";
public const string RmiName_OnGameMatched="OnGameMatched";
public const string RmiName_OnGameInfo="OnGameInfo";
public const string RmiName_OnGameStatusCountdown="OnGameStatusCountdown";
public const string RmiName_OnGameStatusTime="OnGameStatusTime";
public const string RmiName_OnGameStatusReady="OnGameStatusReady";
public const string RmiName_OnGameStatusScore="OnGameStatusScore";
public const string RmiName_OnGameStatusMessage="OnGameStatusMessage";
public const string RmiName_OnGameEventHealth="OnGameEventHealth";
public const string RmiName_OnGameEventDamage="OnGameEventDamage";
public const string RmiName_OnGameEventObject="OnGameEventObject";
public const string RmiName_OnGameEventItem="OnGameEventItem";
public const string RmiName_OnGameEventKill="OnGameEventKill";
public const string RmiName_OnGameEventRespawn="OnGameEventRespawn";
public const string RmiName_OnGameResult="OnGameResult";
public const string RmiName_OnGameUserMove="OnGameUserMove";
public const string RmiName_OnGameUserSync="OnGameUserSync";
       
public const string RmiName_First = RmiName_OnLoginResult;
#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_OnLoginResult="";
public const string RmiName_OnStatusResult="";
public const string RmiName_OnSystemResult="";
public const string RmiName_OnGameMatched="";
public const string RmiName_OnGameInfo="";
public const string RmiName_OnGameStatusCountdown="";
public const string RmiName_OnGameStatusTime="";
public const string RmiName_OnGameStatusReady="";
public const string RmiName_OnGameStatusScore="";
public const string RmiName_OnGameStatusMessage="";
public const string RmiName_OnGameEventHealth="";
public const string RmiName_OnGameEventDamage="";
public const string RmiName_OnGameEventObject="";
public const string RmiName_OnGameEventItem="";
public const string RmiName_OnGameEventKill="";
public const string RmiName_OnGameEventRespawn="";
public const string RmiName_OnGameResult="";
public const string RmiName_OnGameUserMove="";
public const string RmiName_OnGameUserSync="";
       
public const string RmiName_First = "";
#endif
		public override Nettention.Proud.RmiID[] GetRmiIDList() { return Common.RmiIDList; } 
	}
}

